project:
  type: book

book:
  title: "Analysing ANS Performance with R"
  author: "Rainer RQ Koelle"
  date: "2023 development version"
  chapters:
    - index.qmd
    - 01-intro.qmd
    - part: 10-basics.qmd
      chapters:
        - 10-introduction.qmd
        - 02-test.qmd
        - 03-nextchapter.qmd
        - 20-rcrashcourse.qmd
    - part: "Rmagic"
    - 99-references.qmd
    appendices:
    - A1-appendix.qmd
  downloads: [pdf, docx]
  
bibliography: book.bib   #, packages.bib]

format:
  html:
    theme: cosmo
  pdf:
    documentclass: scrreport
  docx: default
# epub:
#    cover-image: cover.png