project:
  type: book

book:
  title: "Analysing ANS Performance with R"
  author: "Rainer RQ Koelle"
  date: "2023 development version"
  chapters:
    - index.qmd
    - 01-intro.qmd
    - 02-test.qmd
    - 03-nextchapter.qmd
    - 99-references.qmd
  downloads: 
    - pdf
    - docx
  
bibliography: book.bib   #, packages.bib]

format:
  html:
    theme: cosmo
  pdf:
    documentclass: scrreport
  docx: default
# epub:
#    cover-image: cover.png