# Preface {.unnumbered}

## About this book {-}

This book documents a journey into using open source software for the operational performance analysis of Air Transportation and Air Navigation Services.
The concepts presented in this book are informed by the experience of a series of international benchmarking projects. 
Discussions in - **and lessons learnt from** - these projects revolved around similar themes. 
This book would have not been possible without the discussions and generous time of all participants in these projects.

The book is written to help researchers, ANS performance analysts, and interested parties in establishing reproducible performance reports in accordance with the international conventions put together by the benchmarking community in response to the Key Performance Indicators proposed by ICAO in the on-going refinement of the Global Air Navigation Plan. 

## Structure of the book {-}

This book is organised in several parts.

* **Part I** provides an introduction to Air Transportation and Air Navigation and sets the scene of our study area of interest.
* **Part II** gives a *getting-up-and-started* crash-course with the R/RStudio Ecosystem. This book cannot distill the many useful introductory books on R, RStudio, various packages, and concepts. However, the information should be enough to replicate the examples and get the interested researcher/practitioner up and running!
* **Part III** introduces the set of operational performance indicators and associated ansperf functions.
* **Part IV** demonstrates use case analyses


```
to be developed
```

